# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MPMVVMTableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MPMVVMTableView

	pod 'SnapKit'

  target 'MPMVVMTableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MPMVVMTableViewUITests' do
    # Pods for testing
  end

end
